#!/bin/bash
# Stop Session Handoff: Generate a handoff document when a session ends.
#
# This is the most critical hook for team continuity. When a session ends
# (developer stops for the day, context runs out, session crash), this hook
# captures the current state so the NEXT session can pick up without re-deriving
# context from scratch.
#
# The handoff document answers: What was I doing? What decisions were made?
# What's left? What assumptions are active? What should I do next?

set -euo pipefail

INPUT=$(cat)

SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // "unknown"')
PROJECT_DIR=$(echo "$INPUT" | jq -r '.cwd // empty')

if [[ -z "$PROJECT_DIR" ]]; then
  PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
fi

HANDOFF_DIR="$PROJECT_DIR/docs/handoff"
mkdir -p "$HANDOFF_DIR"

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
DATE_SLUG=$(date -u +"%Y%m%d-%H%M%S")
HANDOFF_FILE="$HANDOFF_DIR/latest.md"
ARCHIVE_FILE="$HANDOFF_DIR/${DATE_SLUG}.md"

# Gather state
BRANCH=$(cd "$PROJECT_DIR" && git branch --show-current 2>/dev/null || echo "unknown")
UNCOMMITTED=$(cd "$PROJECT_DIR" && git status --porcelain 2>/dev/null | head -30 || true)
RECENT_COMMITS=$(cd "$PROJECT_DIR" && git log --oneline -10 2>/dev/null || true)
STAGED=$(cd "$PROJECT_DIR" && git diff --cached --stat 2>/dev/null || true)

# Check for active backlog items (in-progress)
IN_PROGRESS=""
if [[ -d "$PROJECT_DIR/backlog/in-progress" ]]; then
  IN_PROGRESS=$(ls "$PROJECT_DIR/backlog/in-progress/" 2>/dev/null || true)
fi

# Check for unvalidated assumptions
ASSUMPTIONS=""
if [[ -d "$PROJECT_DIR/docs/engagement" ]]; then
  ASSUMPTIONS=$(grep -rn "ASSUMED" "$PROJECT_DIR/docs/engagement/" 2>/dev/null | head -10 || true)
fi

# Check for recent decisions
RECENT_DECISIONS=""
if [[ -f "$PROJECT_DIR/docs/decisions/session-decisions.md" ]]; then
  RECENT_DECISIONS=$(tail -30 "$PROJECT_DIR/docs/decisions/session-decisions.md" 2>/dev/null || true)
fi

# Check for failing tests or known issues
TEST_STATUS=""
if [[ -f "$PROJECT_DIR/docs/audit/command-log.jsonl" ]]; then
  TEST_STATUS=$(grep '"category":"test-execution"' "$PROJECT_DIR/docs/audit/command-log.jsonl" 2>/dev/null | tail -5 | jq -r '"  " + .timestamp + " | success=" + (.success | tostring) + " | " + .command' 2>/dev/null || true)
fi

# Generate the handoff document
cat > "$HANDOFF_FILE" << EOF
---
session_id: ${SESSION_ID:0:8}
ended_at: ${TIMESTAMP}
branch: ${BRANCH}
---

# Session Handoff — ${TIMESTAMP}

## Current State

**Branch:** \`${BRANCH}\`
**Session:** ${SESSION_ID:0:8}

### Uncommitted Changes
\`\`\`
${UNCOMMITTED:-"(clean working tree — all work committed)"}
\`\`\`

### Staged (not yet committed)
\`\`\`
${STAGED:-"(nothing staged)"}
\`\`\`

## Recent Commits (this session)

\`\`\`
${RECENT_COMMITS:-"(no commits)"}
\`\`\`

## In-Progress Work

${IN_PROGRESS:-"(no items in backlog/in-progress/)"}

## Recent Decisions

${RECENT_DECISIONS:-"(no decisions logged this session — check docs/decisions/)"}

## Unvalidated Assumptions

${ASSUMPTIONS:-"(none — all assumptions validated or no assumptions stated)"}

## Recent Test Results

${TEST_STATUS:-"(no test executions logged)"}

## Next Session Should

1. Review this handoff document
2. Check \`git status\` and \`git log\` for current state
3. Resume the active loop (check backlog/in-progress/)
4. Validate any listed assumptions if possible
5. Run tests to confirm green state

---
*Auto-generated by session handoff hook. Previous handoffs archived in docs/handoff/*
EOF

# Also save as dated archive
cp "$HANDOFF_FILE" "$ARCHIVE_FILE"

# Clean up old archives (keep last 20)
ls -t "$HANDOFF_DIR"/*.md 2>/dev/null | grep -v "latest.md" | tail -n +21 | xargs rm -f 2>/dev/null || true

jq -n --arg file "docs/handoff/latest.md" '{
  "systemMessage": "Session handoff written to \($file). Next session will have full context to resume."
}'
